### PR TITLE
Migrated Package To Null-Safety along with Code Separation

### PR DESCRIPTION
**Pull request by rounaktadvi**
- [x] ✨ Migrated Package To Null-Safety
- [x] 🧹 Added Separation for Code Readability(code refactor)
- [x] 🎸 Added universal_io package for web support(chore)

### CODE REVIEW

**Comment by JErazo7** [comment]
Please merge this ASAP

**Comment by rounaktadvi** [comment]
Since, @komapeb is not active since December 2019, I republished the package at pub.dev

https://pub.dev/packages/internet_connection_checker/versions/0.0.1

**Comment by hectorAguero** [comment]
> Since, @komapeb is not active since December 2019, I republished the package at pub.dev
> 
> https://pub.dev/packages/internet_connection_checker/versions/0.0.1

@RounakTadvi, Since universal_io package use three dependencies, can you use [universal  platform package](https://pub.dev/packages/universal_platform/versions/1.0.0-nullsafety) , btw the null safety version is in prerealse status, I don't know if that is a problem.

**Comment by igoriuz** [comment]
> 
> 
> Since, @komapeb is not active since December 2019, I republished the package at pub.dev
> 
> https://pub.dev/packages/internet_connection_checker/versions/0.0.1

That's actually great but you should've forked this repo instead of creating a completly new one. Give credit where credit is due. Even if most commit messages are non-sense.

**Comment by rounaktadvi** [comment]
@igoriuz Okay

**Comment by JaffaKetchup** [comment]
Hello, any news on this?

**Comment by MrCsabaToth** [comment]
> @igoriuz Okay

It's still not a fork

**Pull request closed without merging**
